    create table users (
                           created_at timestamp(6) not null,
                           id bigint generated by default as identity,
                           updated_at timestamp(6) not null,
                           default_view varchar(20) not null check (default_view in ('MONTH','WEEK','DAY')),
                           role varchar(20) not null check (role in ('ROLE_USER','ROLE_ADMIN')),
                           user_status varchar(20) not null check (user_status in ('ACTIVE','BLOCKED','DELETED')),
                           provider varchar(50) not null check (provider in ('LOCAL','GOOGLE')),
                           name varchar(100) not null,
                           profile_image_url varchar(2048),
                           email varchar(255) not null unique,
                           password varchar(255),
                           provider_id varchar(255),
                           primary key (id)
    );

    create table projects (
        end_date date not null,
        start_date date not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        owner_id bigint not null,
        updated_at timestamp(6) not null,
        name varchar(200) not null,
        status varchar(255) not null check (status in ('IN_PROGRESS','COMPLETED')),
        primary key (id)
    );

    create table refresh_tokens (
        created_at timestamp(6) not null default now(),
        updated_at timestamp(6) not null default now(),
        expires_at timestamp(6) not null,
        id bigint generated by default as identity,
        revoked_at timestamp(6),
        user_id bigint not null,
        device_info varchar(255) not null,
        token_hash bytea not null,
        primary key (id),
        constraint uk_token_hash unique (token_hash)
    );
-- 조회 보조 인덱스 (활성만 대상인 부분 인덱스 권장)
    create index idx_user_active 
       on refresh_tokens (user_id, expires_at);
-- FK들
    alter table if exists projects 
       add constraint fk_projects_owner 
       foreign key (owner_id) references users;
    alter table if exists refresh_tokens 
       add constraint fk_refresh_token_user 
       foreign key (user_id) references users;
-- 부분 유니크 인덱스: 활성(revoked_at IS NULL)일 때만 유니크
    create unique index uq_refresh_active
        on refresh_tokens (user_id, device_info)
        where revoked_at is null;