-- 초대 테이블 (PostgreSQL)
-- 엔티티: cola.springboot.cocal.invite.Invite
create table invites (
                         id bigint generated by default as identity,
                         project_id bigint not null,
                         email varchar(255) not null,
                         invited_by bigint,
                         status varchar(20) not null check (status in ('PENDING','ACCEPTED','DECLINED','EXPIRED')),
                         token char(64) not null unique,
                         expires_at timestamp(6),
                         created_at timestamp(6) not null default current_timestamp(6),

                         constraint uk_invite_project_email unique (project_id, email),

                         constraint fk_inv_project
                             foreign key (project_id) references projects(id)
                                 on update cascade on delete cascade,

                         constraint fk_inv_inviter
                             foreign key (invited_by) references users(id)
                                 on update cascade on delete set null,

                         primary key (id)
);

create index idx_inv_project on invites(project_id);

